version: "3.2"

services:

  haproxy:
    image: ha_proxy
    hostname: "haproxy"
    depends_on:
      - app
    ports:
    - "8443:8443"
    - "8080:8080"
    - "1936:1936"

  app:
    image: ha_app
    deploy:
      endpoint_mode: dnsrr
      replicas: 2

